#! /usr/bin/bash

cat train-v2.0.json | jq '[. | .data | .[] | .t=(.title) | .paragraphs | .[] | .questions=([.qas | .[] | .question]) | .ans=([.qas | .[] | .. | .text?]) | {context: .context, questions:.questions, ans:.ans}]'> easy_training_2.json

#ipython ./proyecto_final.py
#comente la linea pasada porque es exactamente lo mismo que tiene el notebook
